version: '3.8'

services:
  md-pdf-mcp:
    build: .
    image: md-pdf-mcp:latest
    container_name: md-pdf-mcp-server
    stdin_open: true
    tty: true
    volumes:
      # Mount a directory for markdown files and output
      - ./data:/data
    working_dir: /data
    command: python -m md_pdf_mcp.server

# Usage:
# docker-compose up -d    # Start server in background
# docker-compose down     # Stop server
# docker-compose logs     # View logs
#
# Note: This provides DOCX conversion only.
# PDF conversion requires Windows + Microsoft Word (not available in containers)
